name: Run all tests

on:
  push:
    branches: [ "master" ] # Run on pushes to the main branch
  pull_request:
    branches: [ "master" ] # Run on pull requests targeting the main branch

jobs:
  test:
    timeout-minutes: 60 # Set a timeout for the job
    runs-on: ubuntu-latest # Use Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci #

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests on qa
      run: npx playwright test --project qa --reporter=github,list,html,junit

    - name: Upload Playwright report
      if: always() # Always run this step, even if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/

    - name: Upload Playwright traces
      if: failure() # Only upload traces if tests fail
      uses: actions/upload-artifact@v4
      with:
        name: playwright-traces
        path: test-results/
        retention-days: 2 # Keep traces for 5 days